services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check-du-matin-blade-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.prod:/var/www/.env  # <- ton vrai .env
      - app_storage:/var/www/storage
      - ./wait-for-mysql.php:/var/www/wait-for-mysql.php
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://checking.c2s.fr
      ASSET_URL: https://checking.c2s.fr
      SESSION_SECURE_COOKIE: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: check_du_matin
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      MAIL_MAILER: smtp
      MAIL_HOST: relais.services.c-2-s.info
      MAIL_PORT: 25
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_DSN: smtp://relais.services.c-2-s.info:25?encryption=null&verify_peer=0&verify_peer_name=0
      MAIL_VERIFY_PEER: "false"
      MAIL_VERIFY_PEER_NAME: "false"
      MAIL_ALLOW_SELF_SIGNED: "true"
    command: >
      bash -c "
        mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache &&
        mkdir -p storage/app &&
        chmod -R 775 storage bootstrap/cache &&
        if [ ! -f storage/app/initialized ]; then
          php artisan key:generate --force
          touch storage/app/initialized
        fi &&
        php /var/www/wait-for-mysql.php &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan storage:link || true &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        php -S 0.0.0.0:8000 -t public
      "


  db:
    image: mysql:8.0
    container_name: check-du-matin-blade-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: check_du_matin
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
  app_storage:
