services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check-du-matin-blade-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./.env.prod:/var/www/.env  # <- ton vrai .env
      - app_storage:/var/www/storage
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_HOST: db
      DB_DATABASE: check_du_matin
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    command: >
      bash -c "
        mkdir -p storage/framework/{cache,sessions,views} bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache &&
        if [ ! -f storage/app/initialized ]; then \
          php artisan key:generate --force; \
          php artisan migrate --force; \
          php artisan db:seed --class=CompleteSeeder --force; \
          touch storage/app/initialized; \
        fi && \
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        php -S 0.0.0.0:8000 -t public
      "


  db:
    image: mysql:8.0
    container_name: check-du-matin-blade-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: check_du_matin
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_storage:
